apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        timestamp: "{{ now | date "20060102150405" }}"
      labels:
        {{- include "charts.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "charts.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AUTH0_SECRET
              value: {{ .Values.env.authSecret }}
            - name: AUTH0_ISSUER_BASE_URL
              value: {{ .Values.env.authIssuerUrl }}
            - name: AUTH0_CLIENT_ID
              value: {{ .Values.env.authClientId }}
            - name: AUTH0_CLIENT_SECRET
              value: {{ .Values.env.authClientSecret }}
            - name: AUTH0_AUDIENCE
              value: {{ .Values.env.authAudience }}
            - name: AUTH0_SCOPE
              value: {{ .Values.env.authScope }}
            - name: BACK_URL
              value: {{ .Values.env.backUrl }}
            - name: TEST_MODE
              value: "{{ .Values.env.testMode }}"
            - name: APIKEY
            value: "{{ .Values.env.apiKey }}"
            - name: AIGENERATION_URL
            value: "{{ .Values.env.aiGenerationUrl }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
